env:
  CGO_ENABLED: 0
  GOARCH: amd64
  APP_NAME: art
  E_NUMBER: 10
  C_NUMBER: 5
  ART_E_VERSION: 0.1.${E_NUMBER}
  ART_C_VERSION: 1.0.${C_NUMBER}
  GOOS: darwin
  E_VERSION: "${ART_E_VERSION} (enterprise), build: ${ARTISAN_REF}"
  C_VERSION: "${ART_C_VERSION} (community), build: ${ARTISAN_REF}"
  DEB_ENT_VER: 0.1.${E_NUMBER}
  RPM_ENT_VER: 0.1-${E_NUMBER}.rhl8
  DEB_COMM_VER: 1.0.${C_NUMBER}
  RPM_COMM_VER: 1.0-${C_NUMBER}.rhl8

functions:
  - name: do
    run:
      - echo ${E_VERSION}